# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: euroins-ssp-api-deployment-stg
  namespace: stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: euroins-ssp-api-stg
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: euroins-ssp-api-stg
    spec:
      containers:
      - name: euroins-ssp-api-stg
        image: euroinsprod.azurecr.io/euroins-ssp-api-stg
        resources:
          requests:
            cpu: "100m"
            memory: 128Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        ports:
        - containerPort: 80