# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: euroins-ssp-api-deployment-stg
  namespace: stg
spec:
  replicas: 1
  securityContext:
    runAsNonRoot: true
  selector:
    matchLabels:
      app: euroins-ssp-api-stg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: euroins-ssp-api-stg
    spec:
      containers:
      - name: euroins-ssp-api-stg
        image: euroinsprod.azurecr.io/euroins-ssp-api-stg
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 80
